create table if not exists PRACOW_ADMINISTRACJI (
   PRAC_ADM_ID INT NOT NULL auto_increment,
   IMIE VARCHAR(20) default NULL,
   NAZWISKO  VARCHAR(20) default NULL,
   PRIMARY KEY (PRAC_ADM_ID)
);

create table if not exists STUDENCI (
   STUDENT_ID INT NOT NULL auto_increment,
   IMIE VARCHAR(20) default NULL,
   NAZWISKO  VARCHAR(20) default NULL,
   KIERUNEK VARCHAR(20) default NULL,
   RODZAJ_STUDIOW VARCHAR(20) default NULL,
   TRYB_STUDIOW VARCHAR(20) default NULL,
   PRAC_ADM_ID INT default NULL,
   FOREIGN KEY (PRAC_ADM_ID) REFERENCES PRACOW_ADMINISTRACJI (PRAC_ADM_ID),
   PRIMARY KEY (STUDENT_ID)
);


create table if not exists PROWADZACY (
   PROWADZACY_ID INT NOT NULL auto_increment,
   IMIE VARCHAR(20) default NULL,
   NAZWISKO  VARCHAR(20) default NULL,
   PRAC_ADM_ID INT not NULL,
   FOREIGN KEY (PRAC_ADM_ID) REFERENCES PRACOW_ADMINISTRACJI (PRAC_ADM_ID),
   PRIMARY KEY (PROWADZACY_ID)
);

create table if not exists ZAJECIA ( 
	ZAJECIA_ID INT NOT NULL auto_increment,
	NAZWA_ZAJEC VARCHAR(255) default null,
	PROWADZACY_ID INT not null, 
	TYP_ZAJEC VARCHAR (20) not NULL,
	CONSTRAINT `fk_prowadzacy` FOREIGN KEY (`PROWADZACY_ID`) REFERENCES `PROWADZACY` (`PROWADZACY_ID`), 
	PRIMARY KEY (ZAJECIA_ID) 
	);

create table if not exists STUD_ZAJ_REL (
	STUDENT_ID INT NOT NULL,
	ZAJECIA_ID INT NOT NULL,
	PRIMARY KEY (`STUDENT_ID`,`ZAJECIA_ID`),
	CONSTRAINT `fk_student` FOREIGN KEY (`STUDENT_ID`) REFERENCES `STUDENCI` (`STUDENT_ID`),
	CONSTRAINT `fk_zajecia` FOREIGN KEY (`ZAJECIA_ID`) REFERENCES `ZAJECIA` (`ZAJECIA_ID`)
);

